steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean','package', '-forder-api/pom.xml']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/sanguine-form-292516/order-api:V1', './order-api']
images: ['gcr.io/sanguine-form-292516/order-api']