apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: order-api
  name: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: order-api
    spec:
      containers:
      - image: webshop/order-api
        name: order-api
        imagePullPolicy: Never
        env:
              - name: SPRING_PROFILES_ACTIVE
                value: "cloud"
              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    name: postgres-config
                    key: POSTGRES_USER
              - name: POSTGRES_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: postgres-config
                    key: POSTGRES_PASSWORD
              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    name: postgres-config
                    key: POSTGRES_DB

        resources: {}
status: {}
